# -*- coding: utf-8 -*-
"""Cópia de EXERCICIO 3 -NIAS-IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BupbaeW3Kvab0q0n1Pnpjft5xqTI5ahR
"""

tweets = [
"Wow, what a great day today!! #sunshine",
"I feel sad about the things going on around us. #covid19",
"I'm really excited to learn Python with @JovianML #zerotopandas",
"This is a really nice song. #linkinpark",
"The python programming language is useful for data science",
"Why do bad things happen to me?",
"Apple announces the release of the new iPhone 12. Fans are excited.",
"Spent my day with family!! #happy",
"Check out my blog post on common string operations in Python. #zerotopandas",
"Freecodecamp has great coding tutorials. #skillup"]

#Quantos tweets existem nesse banco de dados?

Quantidade_tweets= len(tweets)
print(Quantidade_tweets)

happy_words = ['great', 'excited', 'happy', 'nice', 'wonderful', 'amazing', 'good', 'best']
sad_words = ['sad', 'bad', 'tragic', 'unhappy', 'worst']

num=0
def verificar():
  for i in sad_words:
    if i in tweets[num]:
      print('Tweet Triste')
  for g in happy_words:
    if g in tweets[num]:
      print('Tweet Feliz')
end=('')


verificar()

lista_sad=[]
lista_happy=[]
NS=len(tweets)

def verificando():
  for lista in range(NS):
    for i in sad_words:
      if i in tweets[lista]:
        lista_sad.append(tweets[lista])
    for g in happy_words:
      if g in tweets[lista]:
        lista_happy.append(tweets[lista])

verificando()


h=len(lista_happy)
s=len(lista_sad)
print(lista_sad)
print(lista_happy)



print('na lista tweets tem', h , 'tweets felizes')
print('na lista tweets tem', s , 'tweets triste')